import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import NavBar from "./components/NavBar";
import "./globals.css";
import { headers } from "next/headers";
import dynamic from "next/dynamic";

const NavBarBackground = dynamic(
  () => import("./components/NavBarBackground"),
  { ssr: !!false }
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Game Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <NavBarBackground>
            <NavBar />
          </NavBarBackground>
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
