import type { Metadata } from "next";
import styles from "./styles/home.module.css";
import { Grid } from "@mui/material";

export const metadata: Metadata = {
  title: "Game Hub",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <Grid container>
      <Grid className={styles.home_landing_container} container>
        <Grid component={"div"} className={styles.home_landing_box}></Grid>
      </Grid>
    </Grid>
  );
};

export default Home;
