import { Metadata } from "next";
import { Grid, Typography } from "@mui/material";
import dynamic from "next/dynamic";
import styles from "../styles/games.module.css";
import LoadingSpinner from "../components/global_components/LoadingSpinner";

const SearchBar = dynamic(
  () => import("../components/global_components/SearchBar"),
  {
    ssr: !!false,
  }
);

const TopRatedList = dynamic(
  () => import("../components/games_components/TopRatedList"),
  {
    ssr: !!false,
    loading: () => <LoadingSpinner spinnerSize={60} />,
  }
);

// const TopRatedList = dynamic(
//   () =>
//     new Promise<typeof import("../components/games_components/TopRatedList")>(
//       (resolve) => {
//         setTimeout(() => {
//           resolve(import("../components/games_components/TopRatedList"));
//         }, 10000); // 2-second delay
//       }
//     ),
//   {
//     ssr: !!false,
//     loading: () => <LoadingSpinner spinnerSize={60} />,
//   }
// );

const GameList = dynamic(
  () => import("../components/games_components/GameList"),
  {
    ssr: !!false,
    loading: () => <LoadingSpinner spinnerSize={100} />,
  }
);

// const GameList = dynamic(
//   () =>
//     new Promise<typeof import("../components/games_components/GameList")>(
//       (resolve) => {
//         setTimeout(() => {
//           resolve(import("../components/games_components/GameList"));
//         }, 11000); // 2-second delay
//       }
//     ),
//   {
//     ssr: !!false,
//     loading: () => <LoadingSpinner spinnerSize={100} />,
//   }
// );

export const metadata: Metadata = {
  title: "Game Hub - Games",
  description: "Generated by create next app",
};

const Games = () => {
  return (
    <>
      <SearchBar />
      <Grid container id={styles.games_container}>
        <Typography variant="h1" id={styles.games_page_header}>
          Explore Our Library of Games
        </Typography>
        <Grid>
          <Grid id={styles.top_rated_container}>
            <Typography variant="h2" id={styles.top_rated_header}>
              Top Rated Games
            </Typography>
            <Grid>
              <TopRatedList />
            </Grid>
          </Grid>
          <Grid id={styles.game_list_container}>
            <GameList />
          </Grid>
        </Grid>
      </Grid>
    </>
  );
};
export default Games;
