import { Metadata } from "next";
import { Grid } from "@mui/material";
import dynamic from "next/dynamic";

const SearchBar = dynamic(() => import("../components/SearchBar"), {
  ssr: !!false,
});

export const metadata: Metadata = {
  title: "Game Hub - Games",
  description: "Generated by create next app",
};

export default function Games() {
  return (
    <>
      <SearchBar />
      <Grid>HI</Grid>
    </>
  );
}
