# Generated by Django 5.2 on 2025-04-22 16:57

from django.db import migrations, models
from django.db.migrations.operations import RunSQL

def enable_pg_trgm(apps, schema_editor):
    schema_editor.connection.cursor().execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')

class Migration(migrations.Migration):

    dependencies = [
        # Specify your app's last migration here
    ]

    operations = [
        migrations.RunPython(enable_pg_trgm),
    ]
