# Generated by Django 5.2 on 2025-04-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='storyline',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
