# Generated by Django 5.2 on 2025-04-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0003_game_storyline_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
