# Generated by Django 5.2 on 2025-04-22 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0005_remove_game_screenshots_remove_game_videos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameHub.game'),
        ),
        migrations.AlterField(
            model_name='video',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameHub.game'),
        ),
    ]
