# Generated by Django 5.2 on 2025-04-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0006_alter_screenshot_game_alter_video_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='src',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='src',
            field=models.URLField(),
        ),
    ]
