# Generated by Django 5.2 on 2025-04-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0007_alter_screenshot_src_alter_video_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='storyline',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
