# Generated by Django 5.2 on 2025-04-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0008_alter_game_storyline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
