# Generated by Django 5.2 on 2025-04-23 20:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0010_alter_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='game_search_vector_idx'),
        ),
    ]
