# Generated by Django 5.2 on 2025-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0012_game_gamehub_gam_release_d0debc_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='GameHub_gam_title_46bb39_idx'),
        ),
    ]
