# Generated by Django 5.2 on 2025-04-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0013_game_gamehub_gam_title_46bb39_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating'], name='GameHub_gam_rating_3e245d_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title', 'release'], name='GameHub_gam_title_29868a_idx'),
        ),
    ]
