# Generated by Django 5.2 on 2025-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0015_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/blank-profile-picture.png', null=True, upload_to='profile_pics/'),
        ),
    ]
