# Generated by Django 5.2 on 2025-04-28 00:04

import GameHub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0018_alter_passwordrecoverytoken_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordrecoverytoken',
            name='expiration_date',
            field=models.DateTimeField(default=GameHub.models.expiration_time),
        ),
    ]
