# Generated by Django 5.2 on 2025-04-30 19:24

import GameHub.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0019_passwordrecoverytoken_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/blank-profile-picture.png', upload_to='profile_pics/', validators=[GameHub.validators.validate_exact_dimensions, GameHub.validators.validate_image_size]),
        ),
    ]
