# Generated by Django 5.2 on 2025-04-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0020_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/blank-profile-picture.png', upload_to='profile_pics/'),
        ),
    ]
