# Generated by Django 5.2 on 2025-05-01 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0021_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_visiblity',
            field=models.CharField(choices=[('allow', 'Allow'), ('hide', 'Hide')], default='allow', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_last_seen',
            field=models.CharField(choices=[('allow', 'Allow'), ('hide', 'Hide')], default='allow', max_length=20),
        ),
    ]
