# Generated by Django 5.2 on 2025-05-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0023_rename_profile_visiblity_profile_profile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_last_seen',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='allow', max_length=20),
        ),
    ]
