# Generated by Django 5.2 on 2025-05-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0024_alter_profile_show_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='show_last_seen',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=20),
        ),
    ]
