# Generated by Django 5.2 on 2025-05-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0025_alter_profile_show_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_last_seen',
        ),
    ]
