# Generated by Django 5.2 on 2025-05-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0027_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_visibility',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='hidden', max_length=20),
        ),
    ]
