# Generated by Django 5.2 on 2025-05-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0028_profile_name_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_visibility',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=20),
        ),
    ]
