# Generated by Django 5.2 on 2025-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0032_delete_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments_made',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts_made',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
