# Generated by Django 5.2 on 2025-05-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0033_profile_comments_made_profile_posts_made'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='comments_made',
            new_name='comment_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='posts_made',
            new_name='post_count',
        ),
    ]
