# Generated by Django 5.2.1 on 2025-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameHub', '0035_game_release_title_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='GameHub_gam_release_d0debc_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='GameHub_gam_rating_3e245d_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='GameHub_gam_title_29868a_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release', 'title'], name='GameHub_gam_release_91391f_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating', 'title'], name='rating_title_idx'),
        ),
    ]
