# Generated by Django 5.2 on 2025-05-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_forumpost_comment_count_comment'),
        ('GameHub', '0032_delete_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_posts', to='GameHub.game'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(choices=[('game', 'Game'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
