# Generated by Django 5.2 on 2025-05-02 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_forumpost_game_forumpost_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
