# Generated by Django 5.2 on 2025-05-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0005_postreaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_pictures/'),
        ),
    ]
