# Generated by Django 5.2 on 2025-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0007_alter_postreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
