# Generated by Django 5.2 on 2025-05-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0008_alter_forumpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(max_length=30000),
        ),
    ]
